### ISSUE TITLE
Running the project on gradle

### ISSUE THREAD

**Issue by Epicpoop21** [Tutorials-By-Kaupenjoe/Fabric-Tutorial-1.17.1#3]
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '16'
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '16'
2 warnings
[crash-2021-11-02_17.47.12-client.txt](https://github.com/Tutorials-By-Kaupenjoe/Fabric-Tutorial-1.17.1/files/7462969/crash-2021-11-02_17.47.12-client.txt)

**Comment by Kaupenjoe** [comment]
Hey there Epicpoop21, 
the warning has nothing to do with the crash. Make sure that the entrypoints "main" given in the fabric.mod.json file is the same as you packet structure. Taking a look at the tutorial might help, there are quite a few steps that have to be correctly followed: https://www.youtube.com/playlist?list=PLKGarocXCE1FKR-UzlU1l9qrPhnE36qFe

**Comment by Epicpoop21** [comment]
Thank you, this fixed the problem!
